services:
  portfolio:
    security_opt:
      - apparmor:unconfined
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "6769:6769"
    restart: "unless-stopped"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
